apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
  namespace: clickhouse
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  configuration:
    users:
      ingest/password: ingest-pass
      ingest/profile: "clickhouse_operator"
      ingest/quota: default
      ingest/access_management: "1"
      ingest/networks/ip.1: "::1"
      ingest/networks/ip.2: "127.0.0.1"
      ingest/networks/ip.3: "10.0.0.0/8"

    clusters:
      - name: clickhouse
        layout:
          shardsCount: 1
          replicasCount: 1
        templates:
          podTemplate: default
          serviceTemplate: default

  templates:
    podTemplates:
      - name: default
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:24.6
              ports:
                - name: http
                  containerPort: 8123
                - name: tcp
                  containerPort: 9000
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "500m"
                limits:
                  memory: "4Gi"
                  cpu: "2"
              readinessProbe:
                httpGet:
                  path: /ping
                  port: 8123
                initialDelaySeconds: 30
                timeoutSeconds: 3
                periodSeconds: 5
                failureThreshold: 5
              livenessProbe:
                httpGet:
                  path: /ping
                  port: 8123
                initialDelaySeconds: 90
                timeoutSeconds: 3
                periodSeconds: 10
                failureThreshold: 10

    serviceTemplates:
      - name: default
        metadata:
          name: clickhouse
        spec:
          type: ClusterIP
          ports:
            - name: http
              port: 8123
              targetPort: 8123
            - name: tcp
              port: 9000
              targetPort: 9000

#    volumeClaimTemplates: # <— add a PVC so pods can schedule
#      - name: data
#        reclaimPolicy: Retain
#        spec:
#          accessModes: [ "ReadWriteOnce" ]
#          resources:
#            requests:
#              storage: 10Gi
