apiVersion: batch/v1
kind: Job
metadata:
  name: ch-init-job
  namespace: clickhouse
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded,HookFailed
    argocd.argoproj.io/sync-wave: "7"
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: curlimages/curl:8.10.1
          env:
            - name: CH_HOST
              value: "clickhouse-clickhouse.clickhouse.svc.cluster.local:8123"
            - name: CH_USER
              value: "ingest"
            - name: CH_PASS
              value: "ingest-pass"
          command: ["/bin/sh","-c"]
          args:
            - |
              set -euo pipefail
              echo "Waiting for ClickHouse at ${CH_HOST} ..."
              END=$((SECONDS+600))
              until curl -fsS -u "${CH_USER}:${CH_PASS}" "http://${CH_HOST}/?query=SELECT%201" >/dev/null 2>&1; do
                [ ${SECONDS} -ge ${END} ] && echo "Timed out waiting for ClickHouse" && exit 1
                echo "still waiting..."; sleep 3
              done
              echo "Applying init.sql ..."
              curl -fsS -u "${CH_USER}:${CH_PASS}" "http://${CH_HOST}/" --data-binary @/init/init.sql
          volumeMounts:
            - name: init-sql
              mountPath: /init
      volumes:
        - name: init-sql
          configMap:
            name: ch-init-sql
