apiVersion: v1
kind: ConfigMap
metadata:
  name: ch-init-sql
  namespace: clickhouse
data:
  init.sql: |
    -- DB + table (idempotent)
    CREATE DATABASE IF NOT EXISTS events_db;

    CREATE TABLE IF NOT EXISTS events_db.events
    (
      `timestamp` DateTime64(3),   -- ms precision, stored as UTC
      `user_id`   String,
      `action`    String,
      `payload`   String
    )
    ENGINE = MergeTree
    ORDER BY (timestamp, user_id);
    
    CREATE DATABASE IF NOT EXISTS appdb;
    
    CREATE TABLE IF NOT EXISTS appdb.users_cur
    (
    `id`         UInt64,
    `name`       String,
    `email`      String,
    `is_deleted` UInt8           DEFAULT 0,   
    `_op`        UInt8,                       
    `_lsn`       UInt64,                      
    `_ts`        DateTime                      
    )
    ENGINE = ReplacingMergeTree(_lsn)
    ORDER BY (`id`);
        
    -- (Optional) If you want partitions and faster retention operations later:
    -- ENGINE = MergeTree
    -- PARTITION BY toYYYYMMDD(timestamp)
    -- ORDER BY (timestamp, user_id);

    -- Ingest user can insert
    CREATE USER IF NOT EXISTS ingest IDENTIFIED BY 'ingest-pass';
    GRANT INSERT ON events_db.events TO ingest;
    GRANT INSERT ON appdb.users_cur TO ingest;
