apiVersion: batch/v1
kind: Job
metadata:
  name: flink-sql-submit
  namespace: flink
spec:
  template:
    spec:
      serviceAccountName: flink-sa
      restartPolicy: OnFailure
      containers:
        - name: sql-client
          image: ghcr.io/florita1/flink-iceberg:1.17
          command: ["/bin/sh","-lc"]
          args:
            - |
              echo "Submitting Flink SQL to session cluster..."
              /opt/flink/bin/sql-client.sh \
                -D execution.target=kubernetes-session \
                -D kubernetes.cluster-id=flink-session \
                -D kubernetes.namespace=flink \
                -D execution.checkpointing.interval=30s \
                -D table.dynamic-table-options.enabled=true \
                -f /sql/cdc_to_iceberg.sql
          env:
            - name: AWS_REGION
              value: "us-east-1"
          volumeMounts:
            - name: sql
              mountPath: /sql
      volumes:
        - name: sql
          configMap:
            name: flink-sql
