apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  labels:
    app: ingestion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
        - name: ingestion-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: CLICKHOUSE_HOST
              value: {{ .Values.env.clickhouseHost | quote }}
            - name: CLICKHOUSE_USER
              value: {{ .Values.env.clickhouseUser | quote }}
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: password
            - name: CLICKHOUSE_DB
              value: {{ .Values.env.clickhouseDb | quote }}
            - name: CLICKHOUSE_TABLE
              value: {{ .Values.env.clickhouseTable | quote }}

            # Most OTLP HTTP exporters want a scheme
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.otelExporterOtlpEndpoint | quote }}

            - name: METRICS_PORT
              value: {{ .Values.env.metricsPort | quote }}

            - name: MODE
              value: {{ .Values.env.mode | quote }}

            # Align with your app’s envs used in local runs
            - name: REDPANDA_BROKERS
              value: {{ required "env.redpandaBrokers is required" .Values.env.redpandaBrokers | quote }}
            - name: TOPIC
              value: {{ required "env.topic is required" .Values.env.topic | quote }}
            - name: GROUP_ID
              value: {{ required "env.groupId is required" .Values.env.groupId | quote }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}