apiVersion: batch/v1
kind: Job
metadata:
  name: register-debezium-connector
  namespace: debezium
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookFailed
    argocd.argoproj.io/sync-options: Replace=true
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: registrar
          image: curlimages/curl:8.8.0
          volumeMounts:
            - name: cfg
              mountPath: /cfg
          command: ["/bin/sh","-c"]
          args:
            - |
              set -euo pipefail
              # Wait for Connect REST
              until curl -fsS http://connect.debezium.svc.cluster.local:8083/connectors >/dev/null; do
                echo "waiting for Kafka Connect..."; sleep 3
              done
              
              echo "Existing connectors:"
              curl -s http://connect.debezium.svc.cluster.local:8083/connectors | tr -d '\n' && echo
              
              # Create or update
              if curl -s -o /dev/null -w "%{http_code}" http://connect.debezium.svc.cluster.local:8083/connectors/postgres-appdb-connector | grep -q '^200$'; then
                echo "Updating connector…"
                curl -s -i -X PUT -H 'Content-Type: application/json' \
                  --data-binary @/cfg/connector.json \
                  http://connect.debezium.svc.cluster.local:8083/connectors/postgres-appdb-connector/config
              else
                echo "Creating connector…"
                curl -s -i -X POST -H 'Content-Type: application/json' \
                  --data-binary @/cfg/connector.json \
                  http://connect.debezium.svc.cluster.local:8083/connectors
              fi
              
              echo
              echo "Connector status:"
              curl -s http://connect.debezium.svc.cluster.local:8083/connectors/postgres-appdb-connector/status || true
      volumes:
        - name: cfg
          configMap:
            name: debezium-connector
            items:
              - key: connector.json
                path: connector.json
