apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app-password
  POSTGRES_DB: appdb
  POSTGRES_HOST: postgresql.postgres.svc.cluster.local
  POSTGRES_PORT: "5432"
