apiVersion: v1
kind: Service
metadata:
  name: connect
  labels: { app: connect }
spec:
  selector: { app: connect }
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP
