apiVersion: v1
kind: ConfigMap
metadata:
  name: app-init
  namespace: wal-cdc-postgres
data:
  init.sql: |
    -- One-time bootstrap: DB, schema, table, and publication for Debezium
    DO $$ BEGIN
      PERFORM 1 FROM pg_database WHERE datname = 'appdb';
      IF NOT FOUND THEN CREATE DATABASE appdb; END IF;
    END $$;

    \connect appdb

    CREATE SCHEMA IF NOT EXISTS app;

    CREATE TABLE IF NOT EXISTS app.users (
      id          UUID PRIMARY KEY,
      email       TEXT UNIQUE NOT NULL,
      name        TEXT NOT NULL,
      updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
      is_deleted  BOOLEAN NOT NULL DEFAULT false
    );

    -- Debezium reads from a publication; slot will be created by Debezium.
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'dbz_pub') THEN
        CREATE PUBLICATION dbz_pub FOR TABLE app.users;
      END IF;
    END $$;

    -- App user (optional if you prefer secrets managed elsewhere)
    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app') THEN
        CREATE ROLE app LOGIN PASSWORD 'change-me';
      END IF;
    END $$;

    GRANT USAGE ON SCHEMA app TO app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON app.users TO app;
