apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: appdb
  namespace: wal-cdc-postgres
spec:
  instances:
    - name: ha
      replicas: 1
      dataVolumeClaimSpec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  users:
    - name: app
      databases: ["appdb"]
      options: "LOGIN"
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          wal_level: "logical"
          max_wal_senders: 10
          max_replication_slots: 10
          # useful extras; safe defaults:
          hot_standby: "on"
          shared_preload_libraries: "pg_stat_statements"
  databaseInitSQL:
    name: app-init
    key: init.sql
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
