apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wal-cdc-ingestion-secrets
  namespace: wal-cdc-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/florita1/wal-cdc-platform.git
    targetRevision: main
    path: apps/ingestion-secrets
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingestion-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
