apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-operator
  namespace: wal-cdc-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://helm.altinity.com
    chart: altinity-clickhouse-operator
    targetRevision: 0.25.4
    helm:
      releaseName: clickhouse-operator
      values: |
        installCRDs: true
        watchNamespaces: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

