apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-sql
  namespace: wal-cdc-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/florita1/wal-cdc-platform.git
    targetRevision: HEAD
    path: k8s/flink
  destination:
    server: https://kubernetes.default.svc
    namespace: flink
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
