# apps/postgres.yaml (wave 1)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wal-cdc-postgres
  namespace: wal-cdc-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/florita1/wal-cdc-platform.git
    targetRevision: HEAD
    path: manifests/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: wal-cdc-postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
