apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: wal-cdc-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/florita1/wal-cdc-platform
    targetRevision: HEAD
    path: kustomize/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
