apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: wal-cdc-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: redpanda
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.redpanda.com
    chart: redpanda
    targetRevision: 25.1.1
    helm:
      values: |
        statefulset:
          replicas: 1

        storage:
          persistentVolume:
            enabled: false

        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"

        configuration:
          cluster:
            default_topic_replications: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
