apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: wal-cdc-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: redpanda
  source:
    repoURL: https://charts.redpanda.com
    chart: redpanda
    targetRevision: 25.1.1
    helm:
      values: |
        statefulset:
          replicas: 3
        tieredStorage:
          enabled: false
