apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: wal-cdc-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/florita1/wal-cdc-platform.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: wal-cdc-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
